In [213]:
from fastai.vision.all import *
from fastbook import *
import pickle

In [214]:
torch.cuda.is_available()

True

## Image loading

In [215]:
path = untar_data(URLs.MNIST)

In [216]:
def loadImages(paths):
    images = [Image.open(p) for p in paths]
    classes = [p.parent.name for p in paths]
    return (images, classes)

In [217]:
loadImages([
    path/"training"/"5"/"0.png",
    path/"training"/"9"/"10003.png",
    path/"testing"/"4"/"1059.png"
])

([<PIL.PngImagePlugin.PngImageFile image mode=L size=28x28>,
  <PIL.PngImagePlugin.PngImageFile image mode=L size=28x28>,
  <PIL.PngImagePlugin.PngImageFile image mode=L size=28x28>],
 ['5', '9', '4'])

In [218]:
import glob

def allImages(path):
    return list(path.glob("**/*.png"))

testImages = allImages(path)
assert len(testImages) > 0
for image in testImages: assert image.name.endswith(".png") 
len(testImages), type(testImages[0])

(70000, pathlib.WindowsPath)

## Model

In [219]:
class Model:
    def __init__(self, imageSize, categoryCount):
        self.learningEnabled = True
        hiddenSize = imageSize[0] * imageSize[1]
        self.w1 = self.__initParams(imageSize[0] * imageSize[1], hiddenSize)
        self.b1 = self.__initParams(hiddenSize)
        
        self.w2 = self.__initParams(hiddenSize, categoryCount)
        self.b2 = self.__initParams(categoryCount)
        
        self.params = [self.w1, self.b1, self.w2, self.b2]
        
    def applyModel(self, batch):
        hiddenLayer1 = F.relu(batch@self.w1 + self.b1)
        return hiddenLayer1@self.w2 + self.b2
    
    def fit(self, lr):
        if not self.learningEnabled:
            raise Exception("Learning is diabled")
            
        for p in self.params:
            p.data -= p.grad.data * lr
            p.grad.zero_()
    
    def __initParams(self, *size):
        return (torch.rand(size) * 0.01).requires_grad_()
    
    def disableLearning(self):
        self.learningEnabled = False
        for p in self.params:
            p.requires_grad = False

## Learning preparation

### Loss function

In [220]:
def mse(predictedProbabilities, targetProbabilities):
    return torch.square(targetProbabilities - predictedProbabilities).mean()

In [221]:
lossFunction = nn.BCELoss()

In [222]:
test1 = lossFunction(
    tensor([
        [0.7, 0.4, 0.9], # wrong prediction
    ]),
    tensor([
        [0, 0, 1],
    ]).float()
)
test2 = lossFunction(
    tensor([
        [0.6, 0.3, 0.9], # less wrong prediction
    ]),
    tensor([
        [0, 0, 1],
    ]).float()  
)
test1, test2

(tensor(0.6067), tensor(0.4594))

### Other

In [223]:
def calculateAccuracy(targetPredictions, predictions):
    border = 0.5
    return ((predictions > border) == (targetPredictions > border)).all(dim=1).float().mean()

calculateAccuracy(
    tensor([
        [0, 0, 1],
        [0, 1, 0],
        [1, 0, 0]
    ]),
    tensor([
        [0.7, 0.4, 0.9], # wrong prediction
        [0.2, 0.61, 0.48], # correct prediction
        [0.2, 0.1, 0.3] # wrong prediction
    ])
)

tensor(0.3333)

In [224]:
class BatchLoader:
    def __init__(self, images, batchSize):
        self.images = images.copy()
        random.shuffle(self.images)
        self.batchSize = batchSize
        self.nextBatch = 0 
    def nextBatch(self):
        batchStartIndex = min(self.batchSize * self.nextBatch, len(self.images))
        batchEndIndex = min(startBatchFrom + self.batchSize, len(self.images))
        if batchStartIndex == batchEndIndex:
            return None
        else:
            return self.images[batchStartIndex:batchEndIndex]

In [225]:
class BatchLoader:
    def __init__(self, items, batchSize):
        self.items = items.copy()
        random.shuffle(self.items)
        self.batchSize = batchSize
        self.nextBatch = 0 
    def getNextBatch(self):
        batchStartIndex = min(self.batchSize * self.nextBatch, len(self.items))
        batchEndIndex = min(batchStartIndex + self.batchSize, len(self.items))
        if batchStartIndex == batchEndIndex:
            return None
        else:
            self.nextBatch += 1
            return self.items[batchStartIndex:batchEndIndex]
       
    
testItems = [1, 2, 3, 4, 5, 6, 7]
testLoader = BatchLoader(testItems, 4)
receivedItems = testLoader.getNextBatch() + testLoader.getNextBatch()
receivedItems.sort()
assert testItems == receivedItems, "received aren't the same as tests " + receivedItems
assert testLoader.getNextBatch() == None

In [226]:
def loadBatchOfImages(paths):
    images = [tensor(Image.open(p)).view(-1) for p in paths]
    return torch.stack(images).float()/255

In [227]:
def loadBatch(paths):
    images = loadBatchOfImages(paths)
    classes = [p.parent.name for p in paths]
    return (images, classes)
    
testBatchLoader = BatchLoader(allImages(path/"training"), 100)
trainingImages, trainingClasses = loadBatch(testBatchLoader.getNextBatch())
assert len(trainingImages) == len(trainingClasses)

In [228]:
def numberToPrediction(number):
    return [1.0 if i == number else 0.0 for i in range(10)]

def targetPredictions(classes):
    return tensor([numberToPrediction(int(c)) for c in classes])

targetPredictions(["0", "5", "9"])

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### The learning loop

In [240]:
def validateOneBatch(model, batch):
    images, classes = loadBatch(batch)
    predictions = model.applyModel(images).sigmoid()
    print("predictions")
    print(predictions)
    target = targetPredictions(classes)
    print("targets")
    print(target)
    return calculateAccuracy(target, predictions)

validateOneBatch(Model((28,28), 10), allImages(path/"testing/4")[:10])

predictions
tensor([[0.9257, 0.9209, 0.9228, 0.9303, 0.9217, 0.9241, 0.9201, 0.9280, 0.9211, 0.9252],
        [0.7860, 0.7796, 0.7831, 0.7922, 0.7814, 0.7841, 0.7794, 0.7889, 0.7797, 0.7849],
        [0.9251, 0.9201, 0.9220, 0.9298, 0.9207, 0.9238, 0.9196, 0.9274, 0.9203, 0.9241],
        [0.8421, 0.8364, 0.8390, 0.8489, 0.8378, 0.8408, 0.8357, 0.8458, 0.8368, 0.8413],
        [0.8811, 0.8756, 0.8777, 0.8872, 0.8765, 0.8797, 0.8745, 0.8841, 0.8752, 0.8800],
        [0.8248, 0.8185, 0.8210, 0.8313, 0.8196, 0.8225, 0.8178, 0.8275, 0.8184, 0.8234],
        [0.8837, 0.8784, 0.8801, 0.8897, 0.8791, 0.8823, 0.8775, 0.8866, 0.8784, 0.8833],
        [0.8402, 0.8340, 0.8372, 0.8466, 0.8353, 0.8383, 0.8331, 0.8435, 0.8343, 0.8390],
        [0.9211, 0.9162, 0.9182, 0.9260, 0.9169, 0.9197, 0.9153, 0.9237, 0.9163, 0.9202],
        [0.9677, 0.9648, 0.9658, 0.9706, 0.9652, 0.9671, 0.9643, 0.9693, 0.9650, 0.9674]], grad_fn=<SigmoidBackward0>)
targets
tensor([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
 

tensor(0.)

In [230]:
def validateEpoach(model, validationSet, batchSize):
    batchLoader = BatchLoader(validationSet, batchSize)
    batch = batchLoader.getNextBatch()
    accuracies = []
    while batch != None:
        accuracies.append(validateOneBatch(model, batch))
        batch = batchLoader.getNextBatch()
    return round(torch.stack(accuracies).mean().item(), 4)

validateEpoach(Model((28,28), 10), allImages(path/"testing"), 10000)

0.0

In [231]:
def fitOneBatch(model, batch, lr):
    traingingImages, trainingClasses = loadBatch(batch)
    predictions = model.applyModel(traingingImages).sigmoid()
    #print("predictions " + str(predictions))
    target = targetPredictions(trainingClasses)
    #print("target " + str(target))
    criterion = nn.BCEWithLogitsLoss()
    loss = criterion(predictions,target)
    loss.backward()
    #print("Grad w1 " + str(model.w1.grad.mean()) + ", b1 " + str(model.b1.grad.mean()))
    model.fit(lr)
    print("Loss: " + str(loss.item()))

fitOneBatch(Model((28, 28), 10), allImages(path/"training/6")[:10], 1.)

Loss: 1.1406452655792236


In [232]:
def trainEpoach(model, trainingSet, validationSet,  batchSize, lr):
    batchLoader = BatchLoader(trainingSet, batchSize)
    batch = batchLoader.getNextBatch()
    while batch != None:
        fitOneBatch(model, batch, lr)
        batch = batchLoader.getNextBatch()
    accuracy = validateEpoach(model, validationSet, batchSize)
    print("Accuracy " + str(accuracy))
    
model = Model((28, 28), 10)    
trainEpoach(model, allImages(path/"training"), allImages(path/"testing"), 10000, 1.)

Loss: 1.1336984634399414
Loss: 1.0321985483169556
Loss: 0.7815778851509094
Loss: 0.726283848285675
Loss: 0.7160937786102295
Loss: 0.7106762528419495
Accuracy 0.0


In [241]:
model = Model((28, 28), 10)
for e in range(1, 4):
    trainEpoach(model, allImages(path/"training"), allImages(path/"testing"), 10000, 2. / e)

Loss: 1.1328374147415161
Loss: 0.8830285668373108
Loss: 0.7001266479492188
Loss: 0.6992723941802979
Loss: 0.6984172463417053
Loss: 0.6980047821998596
predictions
tensor([[0.0474, 0.0468, 0.0481,  ..., 0.0457, 0.0460, 0.0444],
        [0.0015, 0.0015, 0.0016,  ..., 0.0014, 0.0014, 0.0013],
        [0.0025, 0.0024, 0.0026,  ..., 0.0023, 0.0024, 0.0022],
        ...,
        [0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
        [0.0112, 0.0109, 0.0115,  ..., 0.0106, 0.0107, 0.0102],
        [0.0024, 0.0022, 0.0025,  ..., 0.0022, 0.0022, 0.0021]], grad_fn=<SigmoidBackward0>)
targets
tensor([[0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 1.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.]])
Accuracy 0.0
Loss: 0.6975518465042114
Loss: 0.6973915696144104
Loss: 0.6970617175102234
Loss: 0.6968950033187866
Loss: 0.6967011094093323
Loss: 0.6965

In [234]:
model.disableLearning()
with open('model.pkl', 'wb') as output:
    pickle.dump(model, output, pickle.HIGHEST_PROTOCOL)

In [235]:
def loadModel(path):
    with open(path, 'rb') as file:
        return pickle.load(file)

In [236]:
testModel = loadModel('model.pkl')
testClassificationResult = testModel.applyModel(loadBatchOfImages([path/"testing"/"4"/"1059.png"])).sigmoid()
testMSE = mse(targetPredictions(["4"]), testClassificationResult)
testClassificationResult, testMSE

(tensor([[0.0030, 0.0050, 0.0032, 0.0033, 0.0035, 0.0033, 0.0033, 0.0038, 0.0031, 0.0035]]),
 tensor(0.0993))

In [237]:
validateOneBatch(testModel, allImages(path/"testing"/"4")[:4])

tensor(0.)

In [238]:
import nbformat
import ipynbname

notebook_path = ipynbname.path() 
output_file = "model.py"

# Load the notebook
with open(notebook_path, "r", encoding="utf-8") as f:
    notebook = nbformat.read(f, as_version=4)

# Extract code from cells with the "export" tag
exported_code = []
for cell in notebook.cells:
    if cell.cell_type == "code" and "tags" in cell.metadata:
        if "export" in cell.metadata.tags:
            exported_code.append(cell.source)

# Write the extracted code to a .py file
with open(output_file, "w", encoding="utf-8") as f:
    f.write("\n\n".join(exported_code))

print(f"Exported {len(exported_code)} functions to {output_file}")


Exported 3 functions to model.py
